### ISSUE TITLE
calculate top-k

### ISSUE THREAD

**Issue by 18235273785** [Lung-Yi/rxn_yield_context#2]
how to test test-data and calculate top-k?

**Comment by Lung-Yi** [comment]
I have included the manual in README.md, please follow it:
https://github.com/Lung-Yi/rxn_yield_context?tab=readme-ov-file#evaluate-the-results

**Comment by Lung-Yi** [comment]
I have included the manual in README.md, please follow it:
https://github.com/Lung-Yi/rxn_yield_context?tab=readme-ov-file#evaluate-the-results
