### ISSUE TITLE
error when using the fast use code

### ISSUE THREAD

**Issue by ClarkChan1995** [Lung-Yi/rxn_yield_context#3]
**RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument mat1 in method wrapper_CUDA_addmm)**

When running the code sample, it gives this error. To solve it, please add **.to(self.device)** to line 357 in _evaluation_utils.py_

**Comment by Lung-Yi** [comment]
Thanks for the suggestion! I have modified line 357 in evaluation_utils.py
